CREATE TABLE WATCHLIST
	(LID INTEGER,
 name VARCHAR(50),
	 creationDate DATE,
	 username VARCHAR(20),
	 PRIMARY KEY (LID, username),
	 FOREIGN KEY (username)
		REFERENCES PREMIUM_USER(username)
			ON DELETE CASCADE
ON UPDATE CASCADE)
