DROP TABLE IF EXISTS PREMIUM_USER;
CREATE TABLE PREMIUM_USER
	(username  VARCHAR(20),
	 paymentMethod  VARCHAR(10),
	 PRIMARY KEY (username),
 FOREIGN KEY (username)
REFERENCES USER(username)
ON DELETE CASCADE
ON UPDATE CASCADE)
