DROP TABLE IF EXISTS MOVIE_IN_LIST;
CREATE TABLE MOVIE_IN_LIST
	(MID INTEGER,
	 LID INTEGER,
	 PRIMARY KEY (MID, LID),
	 FOREIGN KEY (MID)
		REFERENCES MOVIE_FP(MID)
			ON DELETE CASCADE
ON UPDATE CASCADE,
 FOREIGN KEY (LID)
		REFERENCES WATCHLIST(LID)
			ON DELETE CASCADE
ON UPDATE CASCADE)
