DROP TABLE IF EXISTS belongs_to;
CREATE TABLE belongs_to
  AS (SELECT movie_id as MID, genre_id as GID
  from movie_genres
      );
ALTER TABLE belongs_to ADD PRIMARY KEY (MID, GID),
	 ADD FOREIGN KEY (MID)
		REFERENCES MOVIE_FP(MID)
			ON DELETE CASCADE
ON UPDATE CASCADE,
 ADD FOREIGN KEY (GID)
		REFERENCES GENRE_FP(GID)
			ON DELETE CASCADE
ON UPDATE CASCADE