DROP TABLE IF EXISTS INTERESTED_IN;
CREATE TABLE INTERESTED_IN
	(username VARCHAR(20),
	 GID INTEGER,
	 PRIMARY KEY (username, GID),
	 FOREIGN KEY (username)
		REFERENCES PREMIUM_USER(username)
			ON DELETE CASCADE
ON UPDATE CASCADE,
 FOREIGN KEY (GID)
		REFERENCES GENRE_fp(GID)
			ON DELETE CASCADE
ON UPDATE CASCADE)
