CREATE TABLE BELONGS_TO
	(MID INTEGER,
	 GID INTEGER,
	 PRIMARY KEY (MID, GID),
	 FOREIGN KEY (MID)
		REFERENCES MOVIE_FP(MID)
			ON DELETE CASCADE
ON UPDATE CASCADE,
 FOREIGN KEY (GID)
		REFERENCES GENRE_FP(GID)
			ON DELETE CASCADE
ON UPDATE CASCADE)
